### ISSUE TITLE
Screenshots aren't downloading in 1.1.0 Linux64

### ISSUE THREAD

**Issue by duganchen** [FreaKzero/ssgl-doom-launcher#19]
I'm using the 1.1.0 linux64 releases. When SSGL tries to download a screenshot, I get the following error:

```
[23221:0928/214543:ERROR:nw_shell.cc(335)] TypeError: undefined is not a function
    at Object.service.lookupWadArchive (file:///tmp/.org.chromium.Chromium.fsfymt/app.js:2:7903)
    at file:///tmp/.org.chromium.Chromium.fsfymt/app.js:2:1484
[23221:0928/214543:INFO:CONSOLE(2)] "Uncaught TypeError: undefined is not a function", source: file:///tmp/.org.chromium.Chromium.fsfymt/app.js (2)
```
If I set up a ./nw dev environment on the master branch and run that, screenshots work fine.

**Comment by FreaKzero** [comment]
Thanks for the report - is already fixed in devbranch
https://github.com/FreaKzero/ssgl-doom-launcher/commit/ed9484a8e56c873b71e43f13d6f193c227aa89b9
