### ISSUE TITLE
AUR Build errors

### ISSUE THREAD

**Issue by ian-mitchell-001** [FreaKzero/ssgl-doom-launcher#44]
Hey, just wanted to let you know there's an AUR build error in `yaourt`. Here's the full terminal output:
```
[ian@quark ~]$ yaourt ssgl
1 core/libgssglue 0.4-2
    Exports a gssapi interface which calls other random gssapi libraries
2 aur/ssgl-doom-launcher-git v1.1.1.r1.gfb54314-4 (0) (0.00)
    Doom Frontend with Oblige mapbuild integration for zdoom, gzDoom, 
    Zandronum, Doom64EX and DoomRPG written in AngularMaterial on NWJS for 
    Windows, Linux and OSX.
==> Enter n° of packages to be installed (e.g., 1 2 3 or 1-3)
==> ---------------------------------------------------------
==> 2


==> Downloading ssgl-doom-launcher-git PKGBUILD from AUR...
x .SRCINFO
x .gitignore
x PKGBUILD
x ssgl-launch
ssgl-doom-launcher-git v1.1.1.r1.gfb54314-4  (2016-11-04 12:41)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> ssgl-doom-launcher-git dependencies:
 - bower (already installed) [makedepend]
 - git (already installed) [makedepend]
 - nodejs-grunt-cli (already installed) [makedepend]


==> Continue building ssgl-doom-launcher-git ? [Y/n]
==> ------------------------------------------------
==> y

==> Building and installing package
==> Making package: ssgl-doom-launcher-git v1.1.1.r1.gfb54314-4 (Sun Apr  1 16:33:07 EDT 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning ssgl-doom-launcher-git git repo...
Cloning into bare repository '/tmp/yaourt-tmp-ian/aur-ssgl-doom-launcher-git/ssgl-doom-launcher-git'...
remote: Counting objects: 4404, done.
remote: Total 4404 (delta 0), reused 0 (delta 0), pack-reused 4404
Receiving objects: 100% (4404/4404), 47.08 MiB | 4.31 MiB/s, done.
Resolving deltas: 100% (2629/2629), done.
  -> Found ssgl-launch
==> Validating source files with sha256sums...
    ssgl-doom-launcher-git ... Skipped
    ssgl-launch ... Passed
==> Extracting sources...
  -> Creating working copy of ssgl-doom-launcher git repo...
Cloning into 'ssgl-doom-launcher-git'...
done.
==> Starting pkgver()...
==> Starting build()...
bower invalid-meta  for:/tmp/yaourt-tmp-ian/aur-ssgl-doom-launcher-git/src/ssgl-doom-launcher-git/bower.json
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower invalid-meta  The "description" is too long, the limit is 140 characters
bower cached        https://github.com/chieffancypants/angular-hotkeys.git#1.7.0
bower validate      1.7.0 against https://github.com/chieffancypants/angular-hotkeys.git#^1.7.0
bower cached        git://github.com/FreaKzero/jQuery-slimScroll.git#1.4.0
bower validate      1.4.0 against git://github.com/FreaKzero/jQuery-slimScroll.git#*
bower cached        https://github.com/angular/bower-angular-animate.git#1.4.6
bower validate      1.4.6 against https://github.com/angular/bower-angular-animate.git#1.4.6
bower cached        https://github.com/angular/bower-angular-aria.git#1.4.6
bower validate      1.4.6 against https://github.com/angular/bower-angular-aria.git#1.4.6
bower cached        https://github.com/angular-ui/angular-ui-router-bower.git#0.2.15
bower validate      0.2.15 against https://github.com/angular-ui/angular-ui-router-bower.git#0.2.15
bower cached        https://github.com/Templarian/MaterialDesign-Webfont.git#1.2.65
bower validate      1.2.65 against https://github.com/Templarian/MaterialDesign-Webfont.git#1.2.65
bower cached        https://github.com/angular/bower-material.git#0.11.4
bower validate      0.11.4 against https://github.com/angular/bower-material.git#0.11.4
bower cached        https://github.com/jquery/jquery-dist.git#2.1.4
bower validate      2.1.4 against https://github.com/jquery/jquery-dist.git#2.1.4
bower cached        https://github.com/angular/bower-angular.git#1.4.6
bower validate      1.4.6 against https://github.com/angular/bower-angular.git#1.4.6
bower cached        https://github.com/jashkenas/underscore.git#1.8.3
bower validate      1.8.3 against https://github.com/jashkenas/underscore.git#1.8.3
bower preinstall    npm install
bower ENOENT        spawn npm ENOENT

Stack trace:
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at Logger.emit (events.js:180:13)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
System info:
Bower version: 1.8.2
Node version: 9.9.0
OS: Linux 4.14.30-1-MANJARO x64
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build ssgl-doom-launcher-git.
==> Restart building ssgl-doom-launcher-git ? [y/N]
==> -----------------------------------------------
==> n
```
Did you make any typos in the `PKGBUILD` file?

**Comment by FreaKzero** [comment]
Sorry for the late response - i just investigated:

im not the maintainer of this Linux package and never communicated to publish this on AUR - someone did this on its own as it seems

And i have no idea why this even exists since you dont need to "build" the old SSGL based on your Linux Kernel (thats the reason why Application Containers like NWJS or Electron are existing)

It seems like:
Based on this: 
https://aur.archlinux.org/packages/ssgl-doom-launcher-git/

And this weird Fork of this guy which i found via github gui
https://github.com/PROPHESSOR/DBFGL_OLD

i think hes the publisher of this package, @PROPHESSOR ?

**Comment by PROPHESSOR** [comment]
Ah?

**Comment by PROPHESSOR** [comment]
[That](https://aur.archlinux.org/packages/ssgl-doom-launcher-git/) isn't my package

**Comment by FreaKzero** [comment]
Hi, 
Sorry i just thought this because of the Username

**Comment by FreaKzero** [comment]
@mdeguzis
Seems like you are the author of the SSGL AUR Package.

Please can you make a delete request for this since its based on a old codebase and the new package script will NOT be compatible with the current Codebase.

I want/will try to manage AUR Packages myself or with help of my contributors/testers.

Thank you
